### ISSUE TITLE
[Bug] 复现卡在的第一步

### ISSUE THREAD

**Issue by zzhhzz666** [yuyi1005/mmrotate#2]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

无

### Reproduces the problem - code sample

无

### Reproduces the problem - command or script

无

### Reproduces the problem - error message

作者大大您好，我阅读了您的这篇文章，想复现一下，但是卡在了第一步，按照正常的复现流程，先找到reamde的各种指令，但是我看您/point2rbox-mmrotate-dev-1.x/configs/point2rbox/README.md  里面只介绍了权重和模型，然后环境要求是有一个/point2rbox-mmrotate-dev-1.x/requirements.txt文件的，我是直接安装这个文件吗？然后训练的各种指令我找了两遍没有找到，所以想问您一下，如有打扰请见谅！祝好

**Comment by wokaikaixinxin** [comment]
> ### Prerequisite
> * [x]  I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.[x]  I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.[x]  The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).
> 
> ### Task
> I'm using the official example scripts/configs for the officially supported tasks/models/datasets.
> 
> ### Branch
> master branch https://github.com/open-mmlab/mmrotate
> 
> ### Environment
> 无
> 
> ### Reproduces the problem - code sample
> 无
> 
> ### Reproduces the problem - command or script
> 无
> 
> ### Reproduces the problem - error message
> 作者大大您好，我阅读了您的这篇文章，想复现一下，但是卡在了第一步，按照正常的复现流程，先找到reamde的各种指令，但是我看您/point2rbox-mmrotate-dev-1.x/configs/point2rbox/README.md 里面只介绍了权重和模型，然后环境要求是有一个/point2rbox-mmrotate-dev-1.x/requirements.txt文件的，我是直接安装这个文件吗？然后训练的各种指令我找了两遍没有找到，所以想问您一下，如有打扰请见谅！祝好
> 
> ### Additional information
> _No response_

您好，我们的项目[ai4rs](https://github.com/wokaikaixinxin/ai4rs)复现了[Point2RBox](https://github.com/wokaikaixinxin/ai4rs/blob/main/projects/Point2Rbox/README.md)。训练和测试指令都有写。
